// *** Generated by G.Dar C++ transpiler v1.00 on 10/10/26 21:09:29
// [** DEBUG **]

// Command line: -Fc; -Fa; -Fl; -Gs; -Gd; 

//	TITLE	programma2.cpp


//****(EXTERN / INCLUDES / PROTOTIPI)
//	//	
//	//	|    5| : .. x 4
//	//	----------------------------------------
void Shape_ctor__i(Shape *this,int n88);
//	//	+---------------------------------------
//	//	----------------------------------------
void Shape_ctor__ic(Shape *this,int n1,char r8);
//	//	+---------------------------------------
//	//	----------------------------------------
void Shape_ctor__(Shape *this);
//	//	----------------------------------------
void Shape_dtor__(Shape *this);
//	//	----------------------------------------
int Shape_op_add__i(Shape *this,int n);
//	//	----------------------------------------
int Shape_buco__ii(Shape *this,int a,int b);
//	//	----------------------------------------
int Shape_buco3__Pc(Shape *this,char * s);
int Shape_buco2__i(Shape *this,int a);		// qua
int Shape_buco2__i(Shape *this,int a);		// qua qua
//	//	|   40| : .. t 2
void Point_ctor__ii(Point *this,int x,int y);		// qua
void Point_ctor__i(Point *this,int x);		// qua
void Point_ctor__F(Point *this,float l);		// qua
//	//	----------------------------------------
char Point_culo1__(Point *this);
void Point_aaa__(Point *this);		// qua qua
//	//	----------------------------------------
int Point_buco2__i(Point *this,int a);
//	//	----------------------------------------
int Point_buco4__i(Point *this,int a);
void Point_dtor__(Point *this);
//	//	----------------------------------------
//	//	+---------------------------------------
//	//	----------------------------------------
void __global_constructors();
//	//	+---------------------------------------
void __global_destructors();
//PUBLIC	_glShape

//EXTRN	__stktop

//**(CONST / STRINGS)
;
const struct Shape_VTable __vftable_Shape = {	
	Shape_buco__ii	,
	Shape_buco3__Pc	,
	Shape_buco2__i	,
	};
	
const struct Point_VTable __vftable_Point = {	
	Shape_buco__ii	,
	Shape_buco3__Pc	,
	Point_buco2__i	,
	Point_buco4__i	,
	};
	

//**(DATA - Inizializzati)
//	<    1>: class Shape {	;
struct	Shape	{
	const struct Shape_VTable *__vptr	;		// x virtual
	int	x;
//	<   10>: x=4;	;
//	<   15>: x=5;	;
	};
	;
//	<   36>: class Point : Shape {	;
struct	Point	{
	struct Shape __base	;		// class
	signed short	t;
	};
	;
//	<   65>: g=1.0; }	;
//	<   65>: int main(short int a) {	;
//PUBLIC		;
//	<   65>: short int y;	;
//	<   66>: sh.buco(3,7);	;
//	<   67>: sh2->buco(3,7);	;
//	<   68>: pt.buco(3,7);	;
//	<   70>: pt.buco4(37);	;

//**(BSS / Struct Instances)

//**(CODE - Metodi e Funzioni)
//		
;
void Shape_ctor__i(Shape *this,int n88) {
	((struct Shape*)this)->__vptr = (const struct Shape_VTable*)&__vftable_Shape;		// x xx virtual
	this->x=4;
	;
__return_end:
;
	}
//		
;
void Shape_ctor__ic(Shape *this,int n1,char r8) {
	((struct Shape*)this)->__vptr = (const struct Shape_VTable*)&__vftable_Shape;		// x xx virtual
	this->x=5;
	;
__return_end:
;
	}
//		
;
void Shape_ctor__(Shape *this) {
	((struct Shape*)this)->__vptr = (const struct Shape_VTable*)&__vftable_Shape;		// x xx virtual
__return_end:
;
	}
//		
;
void Shape_dtor__(Shape *this) {
__return_end:
;
	}
//		
;
int Shape_op_add__i(Shape *this,int n) {
	int	__retval;
	__retval=	n;
	goto __return_end;
//		|   25| : return n;;
__return_end:
;
	return __retval;
	}
//		
;
int Shape_buco__ii(Shape *this,int a,int b) {
	int	__retval;
	__retval=	a-aa;
	goto __return_end;
//		|   28| : return a-b;		;
__return_end:
;
	return __retval;
	}
//		
;
int Shape_buco3__Pc(Shape *this,char * s) {
	int	__retval;
	__retval=	1;
	goto __return_end;
//		|   31| : return 1;;
__return_end:
;
	return __retval;
	}
struct	Shape glShape;		// ;
//		
;
char Point_culo1__(Point *this) {
	char	__retval;
	__retval=	2;
	goto __return_end;
//		|   53| : return '\x2';;
__return_end:
;
	return __retval;
	}
//		
;
int Point_buco2__i(Point *this,int a) {
	int	__retval;
	__retval=	a-aa;
	goto __return_end;
//		|   57| : return a-b;		;
__return_end:
;
	return __retval;
	}
//		
;
int Point_buco4__i(Point *this,int a) {
	int	__retval;
	__retval=	a;
	goto __return_end;
//		|   60| : return a;;
__return_end:
;
	return __retval;
	}
void Point_dtor__(Point *this) {
	Shape_dtor__((struct Shape*)&this->__base);			// chiamo padre
	}
//		
;
void Point_ctor__F(Point *this,float g) {
	Shape_ctor__((struct Shape*)&this->__base);			// chiamo padre
	((struct Point*)this)->__vptr = (const struct Point_VTable*)&__vftable_Point;		// x xx virtual
	g=1.0;
	;
__return_end:
;
	}
//	|   65| : Point::Point(float g) {	g=1.0; };
//		
;
int main(short int a) {
	int	__retval;
__global_constructors();	
	short int	y;		// y
	struct	Point pt3;		// ;
	Point_ctor__ii((struct Point*)&pt3,8,8);	
	struct	Point pt;		// ;
	Point_ctor__F((struct Point*)&pt,1.2);	
	struct	Point pt2;		// ;
	Point_ctor__F((struct Point*)&pt2,3.4);	
	struct	Shape sh;		// ;
	Shape_ctor__((struct Shape*)&sh);	
	struct	Shape *sh2;		// ;
	sh.__vptr->buco__ii((struct Shape*)&sh,3,7);
	sh2->__vptr->buco__ii((struct Shape*)sh2,3,7);
	((const struct Point_VTable*)pt.__base.__vptr)->buco__ii((struct Shape*)&pt,3,7);
	((const struct Point_VTable*)pt.__base.__vptr)->buco4__i((struct Point*)&pt,37);
	__retval=	98;
	goto __return_end;
//		|   73| : return 98;;
//		ENTER;
//			 ossia 4 bytes;
//		LEAVE;
__return_end:
;
	Shape_dtor__(&sh2);			// sh2
	Shape_dtor__(&sh);			// sh
	Point_dtor__(&pt2);			// pt2
	Point_dtor__(&pt);			// pt
	Point_dtor__(&pt3);			// pt3
	__global_destructors();	
	return __retval;
	}
//	;
void __global_constructors() {
	Shape_ctor__(&glShape);			// glShape
	}
void __global_destructors() {
	Shape_dtor__(&glShape);			// glShape
	}

//**** fine traduzione

