// *** Generated by G.Dar C++ transpiler v1.00 on 03/10/26 18:12:04
// [** DEBUG **]

// Command line: -Fc; -Fa; -Fl; -Gs; -Gd; 

//	TITLE	programma.cpp


//****(EXTERN / INCLUDES / PROTOTIPI)
//	//	
void ciao(int a,char b);
//	//	|    9| : .. id 4
//	//	----------------------------------------
void Shape_printId__(Shape *this);
//	//	|   13| : .. x 4
//	//	|   14| : .. y 4
//	//	----------------------------------------
void Shape_muori__(Shape *this);
//	//	----------------------------------------
void Shape_crepa__(Shape *this);
//	//	----------------------------------------
void Shape_ctor__ii(Shape *this,int startX,int startY);
//	//	+---------------------------------------
//	//	----------------------------------------
void Shape_ctor__(Shape *this);
//	//	+---------------------------------------
//	//	----------------------------------------
void Shape_dtor__(Shape *this);
//	//	----------------------------------------
void Shape_print__(Shape *this);
//	//	----------------------------------------
void Shape_print__i(Shape *this,int prefixCode);
//	//	----------------------------------------
void Shape_getX__(Shape *this);
//	//	|   64| : .. aa 4
//	//	|   70| : .. t 2
//	//	----------------------------------------
void Point_ctor__Pc(Point *this,char * s);
//	//	----------------------------------------
void Point_ctor__Pc(Point *this,char * s);
//	//	----------------------------------------
void Point_ctor__Pi(Point *this,int * z);
//	//	----------------------------------------
void Point_scala__i(Point *this,int n);
//	//	----------------------------------------
void Point_move__ii(Point *this,int dx,int dy);
//	//	+---------------------------------------
//	//	----------------------------------------
void Point_ctor__i(Point *this,int h);

//EXTRN	_ciao
//EXTRN	__stktop

//**(CONST / STRINGS)
;

//**(DATA - Inizializzati)
//	<    1>: int ciao(int a,char b=7);	;
//	<    2>: class Shape;			;
//	<    4>: class Shape {	;
struct  Shape {	
	int	id;		// id
	int	x;		// x
	int	y;		// y
//	<   30>: x = startX;	;
//	<   31>: y = startY;	;
//	<   35>: x=y=0;	;
	};
	;
//	<   61>: class Dario {	;
struct  Dario {	
	int	aa;		// aa
	};
	;
//	<   66>: class Point : Shape {	;
struct  Point {	
	struct Shape __base;	;
	signed short	t;		// t
//	<   88>: x += dx;	;
//	<   89>: y += dy;	;
	};
	;

//**(BSS / Struct Instances)

//**(CODE - Metodi e Funzioni)
//		
;
void Shape_printId__(Shape *this) {
	}
//		
;
void Shape_muori__(Shape *this) {
	
	return	3;
//		|   18| : return 3;;
	}
//		
;
void Shape_crepa__(Shape *this) {
	
	return	666;
//		|   21| : return 666;;
	}
//		
;
void Shape_ctor__ii(Shape *this,int startX,int startY) {
	this->x=startX;
	this->y=startY;
	}
//		
;
void Shape_ctor__(Shape *this) {
	this->x=this->y=0;
	}
//		
;
void Shape_dtor__(Shape *this) {
	}
//		
;
void Shape_print__(Shape *this) {
	}
//		
;
void Shape_print__i(Shape *this,int prefixCode) {
	}
//		
;
void Shape_getX__(Shape *this) {
	
	return	this->x;
//		|   55| : return x;;
	}
void Dario_ctor(Dario *this) {
	}
void Dario_dtor(Dario *this) {
	}
;
//		
;
void Point_ctor__Pc(Point *this,char * s) {
	Shape_ctor((Shape*)&this->__base);			// chiamo padre
	}
//		
;
void Point_ctor__Pc(Point *this,char * s) {
	Shape_ctor((Shape*)&this->__base);			// chiamo padre
	}
//		
;
void Point_ctor__Pi(Point *this,int * z) {
	Shape_ctor((Shape*)&this->__base);			// chiamo padre
	}
//		
;
void Point_scala__i(Point *this,int n) {
	
	return	1;
//		|   84| : return 1;;
	}
//		
;
void Point_move__ii(Point *this,int dx,int dy) {
	this->x=dx;
	this->y=dy;
	}
void Point_dtor(Point *this) {
	Shape_dtor((Shape*)&this->__base);			// chiamo padre
	}
;
//		
;
void Point_ctor__i(Point *this,int h) {
	}
//		|   94| : Point::Point(int h) {;
//		;
void __global_constructors() {
	}
void __global_destructors() {
	}

//**** fine traduzione

