// *** Generated by G.Dar C++ transpiler v1.00 on 10/10/26 21:09:47
// [** DEBUG **]

// Command line: -Fc; -Fa; -Fl; -Gs; -Gd; 

//	TITLE	programma.cpp


//****(EXTERN / INCLUDES / PROTOTIPI)
#include <stdlib.h>		// per new/delete/malloc/free//	//	
//	//	----------------------------------------
int minchia(int a);		// qua
int ciao__iii(int a,int b,int c);		// qua
//	//	|   14| : .. id 4
//	//	|   15| : .. id2 4
//	//	----------------------------------------
void Shape_printId__(Shape *this);
//	//	|   20| : .. x 4
//	//	|   21| : .. y 4
void Shape_muori__();		// qua qua
//	//	----------------------------------------
//	//	----------------------------------------
int Shape_crepa__(Shape *this);
//	//	----------------------------------------
void Shape_ctor__ii(Shape *this,int startX,int startY);
//	//	+---------------------------------------
//	//	----------------------------------------
void Shape_ctor__(Shape *this);
//	//	+---------------------------------------
//	//	----------------------------------------
void Shape_dtor__(Shape *this);
//	//	----------------------------------------
void Shape_print__(Shape *this);
//	//	----------------------------------------
void Shape_print__i(Shape *this,int prefixCode);
//	//	----------------------------------------
int Shape_getX__(Shape *this);
//	//	|   79| : .. aa 4
void Dario_ctor__(Dario *this);
void Dario_dtor__(Dario *this);
//	//	|   85| : .. t 2
//	//	----------------------------------------
void Point_ctor__Pc(Point *this,char * s);
//	//	----------------------------------------
void Point_ctor__PPc(Point *this,char * * s);
void Point_ctor__F(Point *this,float l);		// qua
//	//	----------------------------------------
void Point_ctor__(Point *this);
//	//	----------------------------------------
int Point_scala__i(Point *this,int n);
void Point_scala__Pc(Point *this,char * s);		// qua
void Point_scala__Pc(Point *this,char * s);		// qua qua
void Point_Move__i(Point *this,int h);		// qua
void Point_Move__i(Point *this,int h);		// qua qua
//	//	----------------------------------------
void Point_move__ii(Point *this,int dx,int dy);
//	//	+---------------------------------------
//	//	----------------------------------------
//	//	+---------------------------------------
//	//	----------------------------------------
//	//	----------------------------------------
//	//	----------------------------------------
//	//	+---------------------------------------
//	//	|  130| : .. a 4
//	//	|  130| : .. b 4
//	//	|  130| : .. c 4
//	//	----------------------------------------
//	//	+---------------------------------------
//	//	----------------------------------------
void __global_constructors();
//	//	+---------------------------------------
//	//	+---------------------------------------
//	//	+---------------------------------------
//	//	+---------------------------------------
void __global_destructors();
//PUBLIC	_ff
//PUBLIC	_w

//EXTRN	_malloc
//EXTRN	_free
//EXTRN	__stktop

//**(CONST / STRINGS)
;

//**(DATA - Inizializzati)
//	<    1>: int pippo(int a,char c) { return 1; }	;
//PUBLIC		;
//	<    3>: int minchia(int a);	;
//	<    5>: int ciao(int a,int b=7,int c=9);	;
//	<    6>: float ff;	;
//	<    7>: class Shape;			;
struct	Shape;
//	<    9>: class Shape {	;
struct	Shape	{
	const struct Shape_VTable *__vptr	;		// x virtual
	int	id;
	int	x;
	int	y;
//	<   42>: int z;	;
//	<   43>: x = startX;	;
//	<   44>: y = startY;	;
//	<   45>: z=x;	;
//	<   50>: x=y=0;	;
	};
	;
//	<   76>: int Shape::id2=3456;	;
//	<   76>: class Dario {	;
struct	Dario	{
	const struct Dario_VTable *__vptr	;		// x virtual
	int	aa;
	};
	;
//	<   81>: class Point : Shape {	;
struct	Point	{
	struct Shape __base	;		// class
	signed short	t;
//	<  118>: int z;	;
//	<  119>: x += dx;	;
//	<  120>: y += dy;	;
//	<  121>: z=y;	;
//	<  122>: z=dx;	;
	};
	;
//	<  127>: g=1.0;  }	;
//	<  127>: void Point::Move(int h) {	;
//	<  125>: void refTest(int& p, int factor) {	;
//PUBLIC		;
//	<  125>: p*=factor;	;
//	<  127>: struct CULO {	;
struct	CULO	{
	int	a;
	int	b;
	int	c;
	};
	;
//	<  132>: int ciao(int a,int b,int c=9) {	;
//PUBLIC		;
//	<  132>: char *p=new char[32];	;
//	<  133>: p=new Shape;	;
//	<  134>: p=new char;	;
//	<  135>: p=new class Shape;		;
//	<  136>: p=new class Shape(10,7);	;
//	<  137>: p=new struct CULO;			;
//	<  140>: delete p;	;
//	<  143>: int main(int a) {	;
//PUBLIC		;
//	<  143>: short int y;	;
//	<  144>: struct CULO v;	;
//	<  145>: w.a=3;	;
//	<  147>: y=a;	;
//	<  148>: y=Shape::id2;	;
//	<  149>: y=2;	;
//	<  150>: y=pt.x;	;
//	<  151>: pt.print();	;
//	<  152>: pt.print(1);	;
//	<  154>: pt.muori();	;
//	<  157>: pt.move(5, -2);	;
//	<  159>: int finalX = pt.getX();	;
//	<  160>: pt.crepa();	;
//	<  167>: sh2.muori();	;
//	<  168>: ciao(1,2,3);	;
//	<  183>: y=8;	;
//	<  186>: y=225;	;
//	<  188>: pt.crepa();	;

//**(BSS / Struct Instances)
float	ff;		// ff
int	Shape_id2=3456;
struct CULO	w;		// w

//**(CODE - Metodi e Funzioni)
//		
;
int pippo__ic(int a,char c) {
	int	__retval;
	__retval=	1;
	goto __return_end;
//		|    1| : return 1; };
__return_end:
;
	return __retval;
	}
//		
;
void Shape_printId__(Shape *this) {
__return_end:
;
	}
//		
;
void Shape_muori__() {
	goto __return_end;
//		|   26| : return ;;
__return_end:
;
	}
//		
;
int Shape_crepa__(Shape *this) {
	int	__retval;
	__retval=	666;
	goto __return_end;
//		|   29| : return 666;;
__return_end:
;
	return __retval;
	}
//		
;
void Shape_ctor__ii(Shape *this,int startX,int startY) {
	((struct Shape*)this)->__vptr = (const struct Shape_VTable*)&__vftable_Shape;		// x xx virtual
	int	z;		// z
	this->x=startX;
	;
	this->y=startY;
	;
	z=this->x;
	;
//		ENTER;
//			 ossia 4 bytes;
//		LEAVE;
__return_end:
;
	}
//		
;
void Shape_ctor__(Shape *this) {
	((struct Shape*)this)->__vptr = (const struct Shape_VTable*)&__vftable_Shape;		// x xx virtual
	this->y=0;
	this->x=;
	;
__return_end:
;
	}
//		
;
void Shape_dtor__(Shape *this) {
__return_end:
;
	}
//		
;
void Shape_print__(Shape *this) {
__return_end:
;
	}
//		
;
void Shape_print__i(Shape *this,int prefixCode) {
__return_end:
;
	}
//		
;
int Shape_getX__(Shape *this) {
	int	__retval;
	__retval=	this->x;
	goto __return_end;
//		|   70| : return x;;
__return_end:
;
	return __retval;
	}
void Dario_ctor__(Dario *this) {
	this->__vptr = &__vftable_Dario;		// x virtual
	}
void Dario_dtor__(Dario *this) {
	}
//		
;
void Point_ctor__Pc(Point *this,char * s) {
	Shape_ctor__((struct Shape*)&this->__base);			// chiamo padre
	((struct Point*)this)->__vptr = (const struct Point_VTable*)&__vftable_Point;		// x xx virtual
__return_end:
;
	}
//		
;
void Point_ctor__PPc(Point *this,char * * s) {
	Shape_ctor__((struct Shape*)&this->__base);			// chiamo padre
	((struct Point*)this)->__vptr = (const struct Point_VTable*)&__vftable_Point;		// x xx virtual
__return_end:
;
	}
//		
;
void Point_ctor__(Point *this) {
	Shape_ctor__((struct Shape*)&this->__base);			// chiamo padre
	((struct Point*)this)->__vptr = (const struct Point_VTable*)&__vftable_Point;		// x xx virtual
__return_end:
;
	}
//		
;
int Point_scala__i(Point *this,int n) {
	int	__retval;
	__retval=	1;
	goto __return_end;
//		|  111| : return 1;;
__return_end:
;
	return __retval;
	}
//		
;
void Point_move__ii(Point *this,int dx,int dy) {
	int	z;		// z
	this->__base.x+=dx;
	;
	this->__base.y+=dy;
	;
	z=this->__base.y;
	;
	z=dx;
	;
//		ENTER;
//			 ossia 4 bytes;
//		LEAVE;
__return_end:
;
	}
//		
;
void Point_ctor__F(Point *this,float g) {
	Shape_ctor__((struct Shape*)&this->__base);			// chiamo altro
	g=1.0;
	;
__return_end:
;
	}
//	|  127| : Point::Point(float g) : Shape()  {	g=1.0;  };
//		
;
void Point_Move__i(Point *this,int h) {
__return_end:
;
	}
//		
;
void Point_dtor__(Point *this) {
__return_end:
;
	}
//	|  128| : Point::~Point() {	 };
//		
;
void refTest__Rii(int * p,int factor) {
//		cast;
	(*p)*=factor;
	;
__return_end:
;
	}
//		
;
int ciao__iii(int a,int b,int c9) {
	int	__retval;
	char *	p;		// p
//		cast;
	p=(char*)malloc(128);
	;
//		cast;
	p=(struct Shape*)malloc(sizeof(struct Shape));
	Shape_ctor__(p);	
	;
//		cast;
	p=(char*)malloc(1);
	;
//		cast;
	p=(struct Shape*)malloc(sizeof(struct Shape));
	Shape_ctor__(p);	
	;
//		cast;
	p=(struct Shape*)malloc(sizeof(struct Shape));
	Shape_ctor__ii(p,10,7);	
	;
//		cast;
	p=(struct CULO*)malloc(sizeof(struct CULO));
	;
	while( a--)//		beginwhile;
//			|  139| : b++;;
		b++;
//		|  140| : while(a--);
	free(p);
	__retval=	b;
	goto __return_end;
//		|  142| : return b;;
//		ENTER;
//			 ossia 4 bytes;
//		LEAVE;
__return_end:
;
	return __retval;
	}
//		
;
int main(int a) {
	int	__retval;
__global_constructors();	
	short int	y;		// y
	struct CULO	v;		// v
	a3w=;
	y=a;
	;
	y=Shape_id2Shape;
	;
	struct	Point pt;		// ;
	Point_ctor__((struct Point*)&pt);	
	struct	Shape sh;		// ;
	Shape_ctor__((struct Shape*)&sh);	
	struct	Shape sh2;		// ;
	Shape_ctor__ii((struct Shape*)&sh2,10,20);	
	y=2;
	;
//		Shape;		// vado a padre
	y=xpt;
	;
	Shape_print__((struct Shape*)&pt);
	Shape_print__i((struct Shape*)&pt,1);
	Shape_muori__();		// da ProcIsDecl
	Shape_muori__();
	Point_move__ii((struct Point*)&pt,5,-2);
	int	finalX;		// finalX
//		cast;
	finalX=Shape_getX__((struct Shape*)&pt);
	;
	Shape_crepa__((struct Shape*)&pt);
	Shape_muori__();
	ciao__iii(1,2,3);
	if(	y==2 )//			|  180| : y=8;;
		y=8;
		;
//		|  181| : if(y==2);
	if(	y==2 ) {
		y=8;
		;
		}		// %L00009_F//		|  185| : if(y==2) {;
	else	 {		y=225;
		;
		}		//  E00009//		|  188| : else {;
	for(	y=1;
	 ;	y<4 ;//		endfor;
	y++ )	 {		Shape_crepa__((struct Shape*)&pt);
		}		// X_//		|  190| : for(y=1; y<4; y++) {;
	switch(	y ) {
		case 3://			|  193| : case 3:;
			break;
//			|  194| : break;;
		case 31://			|  195| : case 31:;
			break;
//			|  196| : break;;
			default://			|  197| : default:;
			break;
//			|  198| : break;;
//			}	fine switch;
	}
		// endswitch//		|  199| : switch(y) {;
	__retval=	0;
	goto __return_end;
//		|  201| : return 0;;
//		ENTER;
//			 ossia 20 bytes;
//		LEAVE;
__return_end:
;
	Shape_dtor__(&sh2);			// sh2
	Shape_dtor__(&sh);			// sh
	Point_dtor__(&pt);			// pt
	__global_destructors();	
	return __retval;
	}
//	;
void __global_constructors() {
	}
void __global_destructors() {
	}

//**** fine traduzione

