// *** Generated by G.Dar C++ transpiler v1.00 on 09/10/26 00:05:26
// [** DEBUG **]

// Command line: -Fc; -Fa; -Fl; -Gs; -Gd; 

//	TITLE	programma2.cpp


//****(EXTERN / INCLUDES / PROTOTIPI)
//	//	
//	//	|    5| : .. x 4
//	//	----------------------------------------
void Shape_ctor__i(Shape *this,int n);
//	//	+---------------------------------------
//	//	----------------------------------------
void Shape_ctor__(Shape *this);
//	//	----------------------------------------
void Shape_dtor__(Shape *this);
//	//	|   34| : .. t 2
void Point_ctor__F(Point *this,float l);
//	//	|   40| : .. n 1
void Point_dtor__(Point *this);
//	//	----------------------------------------
//	//	+---------------------------------------
//	//	----------------------------------------
void __global_constructors();
void __global_destructors();
//PUBLIC	_glShape

//EXTRN	__stktop

//**(CONST / STRINGS)
;

//**(DATA - Inizializzati)
//	<    1>: class Shape {	;
struct	Shape	{
	int	x;
//	<   19>: x=4;	;
	};
	;
//	<   30>: class Point : Shape {	;
struct	Point	{
	struct Shape __base	;		// class
	signed short	t;
	char	n;
	};
	;
//	<   43>: g=1.0; }	;
//	<   43>: int main(short int a) {	;
//PUBLIC		;
//	<   43>: short int y;	;

//**(BSS / Struct Instances)

//**(CODE - Metodi e Funzioni)
//		
;
void Shape_ctor__i(Shape *this,int n) {
	this->x=4;
	;
__return_end:
;
	}
//		
;
void Shape_ctor__(Shape *this) {
__return_end:
;
	}
//		
;
void Shape_dtor__(Shape *this) {
__return_end:
;
	}
struct	Shape glShape;		// ;
void Point_dtor__(Point *this) {
	Shape_dtor__((Shape*)&this->__base);			// chiamo padre
	}
//		
;
void Point_ctor__F(Point *this,float g) {
	Shape_ctor((Shape*)&this->__base,4);			// chiamo altro
	this->t	= 5;
	g=1.0;
	;
__return_end:
;
	}
//	|   43| : Point::Point(float g) : Shape(4),t(5) {	g=1.0; };
//		
;
int main(short int a) {
	int	__retval;
__global_constructors();	
	short int	y;		// y
	struct	Point pt;		// ;
	Point_ctor__F((Point*)&pt,1.2);	
	struct	Point pt2;		// ;
	Point_ctor__F((Point*)&pt2,3.4);	
	__retval=	0;
	goto __return_end;
//		|   46| : return 0;;
//		ENTER;
//			 ossia 4 bytes;
//		LEAVE;
__return_end:
;
	Point_dtor__(&pt2);			// pt2
	Point_dtor__(&pt);			// pt
	__global_destructors();	
	return __retval;
	}
//	;
void __global_constructors() {
	Shape_ctor__i(&glShape,9);			// glShape
	}
void __global_destructors() {
	Shape_dtor__(&glShape);			// glShape
	}

//**** fine traduzione

