// *** Generated by G.Dar C++ transpiler v1.00 on 04/10/26 23:20:32
// [** DEBUG **]

// Command line: -Fc; -Fa; -Fl; -Gs; -Gd; 

//	TITLE	programma.cpp


//****(EXTERN / INCLUDES / PROTOTIPI)
//	//	
//	//	----------------------------------------
int ciao(int a,char b,int c);
//	//	|   10| : .. id 4
//	//	----------------------------------------
void Shape_printId__(Shape *this);
//	//	|   14| : .. x 4
//	//	|   15| : .. y 4
//	//	----------------------------------------
void Shape_muori__(Shape *this);
//	//	----------------------------------------
int Shape_crepa__(Shape *this);
//	//	----------------------------------------
Shape_ctor__ii(Shape *this,int startX,int startY);
//	//	+---------------------------------------
//	//	----------------------------------------
Shape_ctor__(Shape *this);
//	//	+---------------------------------------
//	//	----------------------------------------
Shape_dtor__(Shape *this);
//	//	----------------------------------------
void Shape_print__(Shape *this);
//	//	----------------------------------------
void Shape_print__i(Shape *this,int prefixCode);
//	//	----------------------------------------
int Shape_getX__(Shape *this);
//	//	|   70| : .. aa 4
//	//	|   76| : .. t 2
//	//	----------------------------------------
Point_ctor__Pc(Point *this,char * s);
//	//	----------------------------------------
Point_ctor__PPc(Point *this,char * * s);
//	//	----------------------------------------
Point_ctor__i(Point *this,int z);
//	//	----------------------------------------
int Point_scala__i(Point *this,int n);
//	//	----------------------------------------
void Point_move__ii(Point *this,int dx,int dy);
//	//	+---------------------------------------
//	//	----------------------------------------
//	//	----------------------------------------
//	//	+---------------------------------------
//	//	|  109| : .. a 4
//	//	|  109| : .. b 4
//	//	|  109| : .. c 4
//	//	----------------------------------------
//	//	----------------------------------------
void __global_constructors();
//	//	+---------------------------------------
//	//	+---------------------------------------
//	//	+---------------------------------------
//	//	+---------------------------------------
void __global_destructors();
//PUBLIC	_ff
//PUBLIC	_w
//PUBLIC	_glShape

//EXTRN	__stktop

//**(CONST / STRINGS)
;

//**(DATA - Inizializzati)
//	<    1>: int pippo(int a,char c) { return 1; }	;
//PUBLIC		;
//	<    1>: int ciao(int a,char b=7,int c=9);	;
//	<    2>: float ff;	;
//	<    3>: class Shape;			;
//	<    5>: class Shape {	;
	int	id;		// id
	int	x;		// x
	int	y;		// y
//	<   35>: x = startX;	;
//	<   36>: y = startY;	;
//	<   41>: x=y=0;	;
	};
	;
//	<   67>: class Dario {	;
	int	aa;		// aa
	};
	;
//	<   72>: class Point : Shape {	;
	struct Shape __base;	;
	signed short	t;		// t
//	<  103>: x += dx;	;
//	<  104>: y += dy;	;
	};
	;
//	<  108>: void Point::Move(int h) {	;
//	<  104>: void refTest(int& p, int factor) {	;
//PUBLIC		;
//	<  104>: p*=factor;	;
//	<  106>: struct CULO {	;
	int	a;		// a
	int	b;		// b
	int	c;		// c
	};
	;
//	<  111>: class Shape glShape;	;
//	<  112>: int ciao(int a,int b,int c) {	;
//PUBLIC		;
//	<  116>: int main(int a) {	;
//PUBLIC		;
//	<  116>: short int y;	;
//	<  117>: struct CULO v;	;
//	<  118>: w.a=3;	;
//	<  120>: y=a;	;
//	<  121>: y=2;	;
//	<  122>: y=pt.x;	;
//	<  123>: pt.print();	;
//	<  124>: pt.print(1);	;
//	<  126>: pt.muori();	;
//	<  127>: pt2.move(5, -2);	;
//	<  129>: int finalX = pt.getX();	;
//	<  130>: y=Point::muori();	;
//	<  133>: pt.crepa();	;
//	<  160>: ciao(3); ciao(15,17); ciao(1,2);	;
//	<  161>: ciao(15,17); ciao(1,2);	;
//	<  161>: ciao(1,2);	;
//	<  165>: y=8;	;
//	<  168>: y=225;	;
//	<  170>: pt.crepa();	;

//**(BSS / Struct Instances)
float	ff;		// ff
struct CULO	w;		// w
class Shape	glShape;		// glShape

//**(CODE - Metodi e Funzioni)
//		
;
int pippo(int a,char c) {
	
	return	1;
//		|    1| : return 1; };
	}
//		
;
void Shape_printId__(Shape *this) {
	}
//		
;
void Shape_muori__(Shape *this) {
	
	return;
//		|   19| : return ;;
	}
//		
;
int Shape_crepa__(Shape *this) {
	
	return	666;
//		|   22| : return 666;;
	}
//		
;
Shape_ctor__ii(Shape *this,int startX,int startY) {
	this->x=startX;
	this->y=startY;
	}
//		
;
Shape_ctor__(Shape *this) {
	this->x=this->y=0;
	}
//		
;
Shape_dtor__(Shape *this) {
	}
//		
;
void Shape_print__(Shape *this) {
	}
//		
;
void Shape_print__i(Shape *this,int prefixCode) {
	}
//		
;
int Shape_getX__(Shape *this) {
	
	return	this->x;
//		|   61| : return x;;
	}
Dario_ctor(Dario *this) {
	}
Dario_dtor(Dario *this) {
	}
;
//		
;
Point_ctor__Pc(Point *this,char * s) {
	Shape_ctor((Shape*)&this->__base);			// chiamo padre
	}
//		
;
Point_ctor__PPc(Point *this,char * * s) {
	Shape_ctor((Shape*)&this->__base);			// chiamo padre
	}
//		
;
Point_ctor__i(Point *this,int z) {
	Shape_ctor((Shape*)&this->__base);			// chiamo padre
	}
//		
;
int Point_scala__i(Point *this,int n) {
	
	return	1;
//		|   96| : return 1;;
	}
//		
;
void Point_move__ii(Point *this,int dx,int dy) {
	this->x=dx;
	this->y=dy;
	}
//		
;
void Point::Move Point_Move__i(Point *this,int h) {
	}
//		
;
void refTest(int & p,int factor) {
	p=factor;
	}
//		
;
int ciao(int a,int b,int c) {
	while( --a)//		beginwhile;
//		|  113| : b++;;
	++b;
//		|  114| : while(a--);
	
	return	b;
//		|  115| : return b;;
	}
//		
;
int main(int a) {
	__global_constructors();	
	short int	y;		// y
	struct CULO	v;		// v
//		GetAdd;
//		StoreDO;
	a3w;
	AND.d;
	y=a;
	Shape_ctor__ii((Shape*)&pt,10,20);	
	Shape_ctor__((Shape*)&pt2);	
	Shape_ctor__((Shape*)&sh);	
	y=2;
//		Shape;		// vado a padre
//		GetAdd;
//		ReadDO;
	y=xpt;
//		Shape;		// chiamo padre
	Shape_print__((Shape*)&pt);	
	;
//		Shape;		// chiamo padre
	Shape_print__i((Shape*)&pt,1);	
	;
	Shape_muori__();	
//		Shape;		// chiamo padre
	Shape_muori__();	
	;
	Point_move__ii((Point*)&pt2,5,2);	
	;
	int	finalX;		// finalX
//		Shape;		// chiamo padre
	Shape_getX__((Shape*)&pt);	
//		GetAdd;
	finalX=ptfinalX;
//		Shape;		// chiamo padre
	Shape_muori__();	
	y=::Point;
//		Shape;		// chiamo padre
	Shape_crepa__((Shape*)&pt);	
	;
	ciao(3,7,9);	
	;
	ciao(15,17,9);	
	;
	ciao(1,2,9);	
	;
	if(	mov;
2y )//		|  162| : y=8;;
	y=8;
//		|  163| : if(y==2);
	if(	mov;
2y ) {	y=8;
//		|  167| : if(y==2) {;
else {	y=225;
//		|  170| : else {;
	for(	y=1;
	mov;
//		endfor;
	++;
	}();			// X_
 {//		Shape;		// chiamo padre
	Shape_crepa__((Shape*)&pt);	
	;
//		|  172| : for(y=1; y<4; y++) {;
	switch(y ) {
		case 3://		|  175| : case 3:;
			break;
//		|  176| : break;;
		case 31://		|  177| : case 31:;
			break;
//		|  178| : break;;
		default://		|  179| : default:;
			break;
//		|  180| : break;;
//		}	fine switch;
		}
		// endswitch//		|  181| : switch(y) {;
	
	return	0;
//		|  183| : return 0;;
//		ENTER;
//			 ossia 20 bytes;
//		LEAVE;
	Point_dtor(&pt);			// pt
	Point_dtor(&pt2);			// pt2
	Shape_dtor(&sh);			// sh
	__global_destructors();	
	}
//		;
void __global_constructors() {
	}
void __global_destructors() {
	}

//**** fine traduzione

