//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CPiuMeno.rc
//
#define IDOK2                           3
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_CTYPE                       129
#define IDR_CTYPE2                      130
#define IDD_OPZIONI_COMPIL              131
#define IDD_OPZIONI_COMPIL_PAGE1        131
#define IDD_SPLASH                      132
#define IDI_CTYPE2                      133
#define IDD_OPZIONI_COMPIL_PAGE2        134
#define IDD_OPZIONI_COMPIL_PAGE3        136
#define IDD_OUTPUT_BAR                  138
#define IDD_TREE_PROJECT                139
#define IDC_RIGHT_CURSOR                139
#define IDR_PROJECTTREE                 140
#define IDR_PROJECTTREE1                141
#define IDB_PROJECTREE                  152
#define IDD_MY_FIND_DIALOG              153
#define IDD_MY_REPLACE_DIALOG           154
#define IDD_GOTO_LINE                   155
#define IDC_CHECK1                      1000
#define IDC_CHECK2                      1001
#define IDC_CHECK3                      1002
#define IDC_CHECK4                      1003
#define IDC_CHECK5                      1004
#define IDC_CHECK6                      1005
#define IDC_CHECK7                      1006
#define IDC_CHECK8                      1007
#define IDC_CHECK9                      1008
#define IDC_CHECK10                     1009
#define IDC_COMBO1                      1010
#define IDC_CHECK11                     1010
#define IDC_CHECK12                     1011
#define IDC_COMBO4                      1011
#define IDC_CHECK13                     1012
#define IDC_COMBO5                      1012
#define IDC_CHECK14                     1013
#define IDC_CHECK15                     1014
#define IDC_CHECK16                     1015
#define IDC_EDIT1                       1016
#define IDC_CHECK17                     1017
#define IDC_COMBO2                      1018
#define IDC_RADIO1                      1019
#define IDC_RADIO2                      1020
#define IDC_TXT_OUTPUT                  1020
#define IDC_COMBO3                      1021
#define IDC_RADIO3                      1021
#define IDC_TXT_OUTPUT2                 1021
#define IDC_CHECK18                     1022
#define IDC_OUTPUT_TAB                  1022
#define IDC_CHECK19                     1023
#define IDC_BUTTON1                     1023
#define IDC_TREE_PROJECT                1024
#define IDC_BUTTON2                     1024
#define IDC_EDIT_LINE                   1024
#define ID_STRUMENTI_SPY                32771
#define ID_COMPILA_FILE                 32772
#define ID_COMPILA_TUTTO                32773
#define ID_COMPILA_ESEGUI               32774
#define ID_COMPILA_IMPOSTAZIONI         32775
#define ID_STRUMENTI_OPZIONI            32776
#define ID_STRUMENTI_PERSONALIZZA       32777
#define ID_FILE_APRIPROGETTO            32778
#define ID_FILE_CHIUDIPROGETTO          32779
#define ID_BUTTON32781                  32781
#define ID_MODIFICA_TROVA               32783
#define ID_MODIFICA_TROVASUCCESSIVO     32784
#define ID_MODIFICA_SOSTITUISCI         32785
#define ID_FILE_SALVATUTTO              32786
#define ID_FILE_NUOVO                   32788
#define ID_EDIT_TROVASELEZIONE          32789
#define ID_EDIT_CERCAINTUTTIIFILE       32790
#define ID_NEXT_ERROR                   32791
#define ID_PREV_ERROR                   32792
#define ID_MODIFICA_INSERISCISEGNALIBRO 32793
#define ID_MODIFICA_VAIALPROSSIMOSEGNALIBRO 32794
#define ID_MODIFICA_VAIALSEGNALIBROPRECEDENTE 32795
#define ID_DEBUG_TOGGLEBREAKPOINT       32796
#define ID_DEBUG_VAI                    32797
#define ID_DEBUG_VAIDENTROFUNZIONE      32798
#define ID_DEBUG_ESCIDAFUNZIONE         32799
#define ID_DEBUG_INTERROMPI             32800
#define ID_DEBUG_TERMINAESECUZIONE      32801
#define ID_FILE_SALVAPROGETTO           32802
#define ID_FILE_SALVAPROGETTOCONNOME    32804
#define ID_FILE_ULTIMOPROGETTOUSATO     32806
#define ID_VISUALIZZA_FINESTRADIOUTPUT  32807
#define ID_VISUALIZZA_FINESTRAPROGETTO  32808
#define ID_FINESTRA_CHIUDITUTTE         32809
#define ID_FILE_NUOVOPROGETTO           32810
#define ID_PROJECT_MRU_FIRST            32820
#define ID_PROJECT_MRU_1                32820
#define ID_PROJECT_MRU_2                32821
#define ID_PROJECT_MRU_3                32822
#define ID_PROJECT_MRU_4                32823
#define ID_PROJECT_MRU_LAST             32823
#define ID_OPEN_INCLUDE_FILE            32824
#define ID_TREE_IMPOSTAZIONI            32827
#define ID_TREE_ESCLUDI                 32828
#define ID_TREE_PROPRIET                32829
#define ID_TREE_OPEN                    32830
#define ID_TREE_ADD                     32831
#define ID_TREE_ELIMINA                 32832
#define ID_COMPILA_COMPILATUTTO         32833
#define ID_PROGETTO_AGGIUNGIFILE        32834
#define ID_COMPILA_FILE2                32835
#define ID_TREE1_NUOVACARTELLA          32836
#define IDC_COMBO_SEARCH                32837
#define IDC_STATIC_SEARCH_LABEL         32838
#define ID_MODIFICA_VAIALLARIGA         32839
#define ID_EDIT_MATCH_BRACE             32840
#define ID_MODIFICA_ELIMINATUTTIISEGNALIBRI 32841
#define ID_EDIT_REPEAT_BACK             32842
#define ID_EDIT_FIND_COMBO              32843
#define IDS_COORDINATE                  61447
#define IDS_FILEAPERTI                  61448
#define IDS_NOMECC                      61449
#define IDS_OPZIONI                     61450
#define IDS_ALTREDEFINE                 61451
#define IDS_MEMORYMODEL                 61452
#define IDS_COORDINATECHILD             61453
#define IDS_WARNING                     61454
#define IDS_ABSREL                      61455
#define ID_INDICATOR_POS                61456
#define IDS_AUTORICARICAPROGETTO        61457
#define IDS_TESTOCOLORATO               61458
#define IDS_CARTELLAINCLUDE             61459
#define IDS_CARTELLALIBRERIE            61460
#define IDS_AUTORICARICAFILES           61461
#define IDS_TABSIZE                     61462

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32844
#define _APS_NEXT_CONTROL_VALUE         1025
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
