// *** Generated by G.Dar C++ transpiler v1.00 on 10/10/26 21:06:28
// [** DEBUG **]

// Command line: -Fc; -Fa; -Fl; -Gs; -Gd; 

//	TITLE	vector.cpp


//****(EXTERN / INCLUDES / PROTOTIPI)
//	//	
//	//	|    3| : .. re 4
//	//	|    3| : .. im 4
//	//	----------------------------------------
int complex_op_add__i(complex *this,int n);
//	//	+---------------------------------------
//	//	----------------------------------------
int complex_op_sub__i(complex *this,int n);
//	//	+---------------------------------------
void complex_ctor__(complex *this);
void complex_dtor__(complex *this);
//	//	----------------------------------------
void __global_constructors();
//	//	+---------------------------------------
void __global_destructors();

//EXTRN	__stktop

//**(CONST / STRINGS)
;

//**(DATA - Inizializzati)
//	<    1>: class complex {	;
struct	complex	{
	const struct complex_VTable *__vptr	;		// x virtual
	int	re;
	int	im;
//	<    5>: im = im+n;	;
//	<    9>: im -= n;	;
	};
	;
//	<   14>: int main() {	;
//PUBLIC		;
//	<   14>: int n;	;
//	<   15>: n=n+1;	;
//	<   17>: c=c+1;	;
//	<   18>: c=c*4;	;

//**(BSS / Struct Instances)

//**(CODE - Metodi e Funzioni)
//		
;
int complex_op_add__i(complex *this,int n) {
	int	__retval;
	this->im=im+´ºthis->im;
	;
	__retval=	re+this->re;
	goto __return_end;
//		|    7| : return re+n;;
__return_end:
;
	return __retval;
	}
//		
;
int complex_op_sub__i(complex *this,int n) {
	int	__retval;
	this->im-=n;
	;
	__retval=	re-this->re;
	goto __return_end;
//		|   11| : return re-n;;
__return_end:
;
	return __retval;
	}
void complex_ctor__(complex *this) {
	this->__vptr = &__vftable_complex;		// x virtual
	}
void complex_dtor__(complex *this) {
	}
//		
;
int main() {
	int	__retval;
__global_constructors();	
	struct	complex c;		// ;
	complex_ctor__((struct complex*)&c);	
	int	n;		// n
	n=n+€Å1nn;
	;
//		cast;
	complex_op_add__i(&c,1);
	MOV.d;
	MOV.w;
	MOV.b;
	DJNZ.w;
	c*€Å4c;
	__retval=	rec;
	goto __return_end;
//		|   21| : return c.re;;
//		ENTER;
//			 ossia 4 bytes;
//		LEAVE;
__return_end:
;
	complex_dtor__(&c);			// c
	__global_destructors();	
	return __retval;
	}
//	;
void __global_constructors() {
	}
void __global_destructors() {
	}

//**** fine traduzione

